name: Build and Push

on:
  push:
    branches:
      - develop
      - "release/**"
    paths-ignore:
      - "*.md"
      - "BUILDMETA"
      - "changelogs/**"
      - "docs/**"
      - "design/**"
      - "LICENSE"
      - "MAINTAINERS"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v22
      - uses: rrbutani/use-nix-shell-action@v1.1.0
        with:
          file: shell.nix

      - name: Check if the chart follows a valid semver version
        run: |
          BRANCH=${{ github.ref_name }}
          ./scripts/validate-chart-version.sh --branch $BRANCH

      - name: Run chart-testing lint
        run: |
          ct lint --config ct.yaml

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go 1.19
        uses: actions/setup-go@v5
        with:
          go-version: 1.19.9
          cache: false

      - name: Set go env
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "GOCACHE=$(go env GOCACHE)" >> $GITHUB_ENV

      - name: Unit test
        run: make test

      - name: Upload Coverage Report
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
          name: coverage-$(date +%s)
          flags: unittests

  bdd-tests:
    needs: ["unit-tests"]
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
      matrix:
        kubernetes: [v1.27.3]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go 1.19
        uses: actions/setup-go@v5
        with:
          go-version: 1.19.9
          cache: false

      - name: Set go env
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "GOCACHE=$(go env GOCACHE)" >> $GITHUB_ENV

      - name: Setup Minikube-Kubernetes
        uses: medyagh/setup-minikube@latest
        with:
          cache: false
          minikube-version: 1.31.1
          driver: none
          kubernetes-version: ${{ matrix.kubernetes }}
          cni: calico
          start-args: "--install-addons=false"

      - name: Build images locally
        run: make lvm-driver-image || exit 1;

      - name: bootstrap
        run: make bootstrap

      - name: Running tests
        env:
          OPENEBS_NAMESPACE: "openebs"
        run: ./ci/ci-test.sh

      - name: Upload Coverage Report
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./tests/bdd_coverage.txt
          name: coverage-bdd_coverage-$(date +%s)
          flags: bddtests

  csi-driver:
    runs-on: ubuntu-latest
    needs: ["lint", "bdd-tests"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Image Org
        run: |
          [ -z "${{ secrets.IMAGE_ORG }}" ] && IMAGE_ORG=openebs || IMAGE_ORG=${{ secrets.IMAGE_ORG }}
          echo "IMAGE_ORG=${IMAGE_ORG}" >> $GITHUB_ENV

      - name: Set Build Date
        id: date
        run: |
          echo "DATE=$(date -u +'%Y-%m-%dT%H:%M:%S%Z')" >> $GITHUB_OUTPUT

      - name: Set IMAGE_TAG and BRANCH
        run: |
          BRANCH=${{ github.ref_name }}
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV
          echo "IMAGE_TAG=$(awk -F': ' '/^version:/ {print $2}' deploy/helm/charts/Chart.yaml)" >> $GITHUB_ENV

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          # add each registry to which the image needs to be pushed here
          images: |
            ${{ env.IMAGE_ORG }}/lvm-driver
            quay.io/${{ env.IMAGE_ORG }}/lvm-driver
            ghcr.io/${{ env.IMAGE_ORG }}/lvm-driver
          tags: |
            type=raw,value=latest,enable=false
            type=raw,value=${{ env.IMAGE_TAG }}

      - name: Print Tag info
        run: |
          echo "BRANCH: ${{ env.BRANCH }}"
          echo "${{ steps.docker_meta.outputs.tags }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.13.1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Quay
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./buildscripts/lvm-driver/Dockerfile.buildx
          push: true
          platforms: linux/amd64, linux/arm64
          tags: |
            ${{ steps.docker_meta.outputs.tags }}
          build-args: |
            DBUILD_DATE=${{ steps.date.outputs.DATE }}
            DBUILD_REPO_URL=https://github.com/openebs/lvm-localpv
            DBUILD_SITE_URL=https://openebs.io
            BRANCH=${{ env.BRANCH }}

  release-chart:
    runs-on: ubuntu-latest
    needs: ["csi-driver"]
    steps:
      - uses: actions/checkout@v4
      - name: Publish lvm localpv develop or prerelease helm chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: ./deploy/helm
