# Copyright 2020 The OpenEBS Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: ci

on:
  pull_request:
    branches:
      - 'develop'
      - 'v*'
    paths-ignore:
      - '*.md'
      - 'BUILDMETA'
      - 'changelogs/**'
      - 'deploy/helm/**'
      - 'docs/**'
      - 'design/**'
      - 'LICENSE'
      - 'MAINTAINERS'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go 1.19
        uses: actions/setup-go@v5
        with:
          go-version: 1.19.9
          cache: false

      - name: Format test
        run: make format

      - name: License test
        run: make license-check

      - name: bootstrap
        run: make bootstrap

      - name: Lint Check
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.56.2
          args: -E exportloopref,dupl,revive,bodyclose,goconst,misspell -D structcheck --timeout 5m0s

      - name: Shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          path: '.'
          pattern: '*.sh'

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go 1.19
        uses: actions/setup-go@v5
        with:
          go-version: 1.19.9
          cache: false

      - name: Unit test
        run: make test

      - name: Upload Coverage Report
        uses: codecov/codecov-action@v4  
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
          name: coverage-$(date +%s)
          flags: unittests

  bdd-test:
    needs: ['unit-test']
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        kubernetes: [v1.27.3]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go 1.19
        uses: actions/setup-go@v5
        with:
          go-version: 1.19.9
          cache: false

      - name: Setup Minikube-Kubernetes
        uses: medyagh/setup-minikube@latest
        with:
          cache: false
          minikube-version: 1.31.1
          driver: none
          kubernetes-version: ${{ matrix.kubernetes }}
          cni: calico
          start-args: '--install-addons=false'

      - name: Build images locally
        run: make lvm-driver-image || exit 1;

      - name: bootstrap
        run: make bootstrap

      - name: Running tests
        run: ./ci/ci-test.sh

      - name: Upload Coverage Report
        uses: codecov/codecov-action@v4  
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./tests/bdd_coverage.txt
          name: coverage-bdd_coverage-$(date +%s)
          flags: bddtests

  csi-driver:
    runs-on: ubuntu-latest
    needs: ['lint', 'unit-test', 'bdd-test']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.13.1

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./buildscripts/lvm-driver/Dockerfile.buildx
          push: false
          platforms: linux/amd64, linux/arm64
          tags: |
            openebs/lvm-driver:ci
